### ISSUE TITLE
How to integrate your TestTools into my own project?

### ISSUE THREAD

**Issue by Vector3q** [keijiro/TestTools#3]
So sorry for that I am a newcomer to Unity. Can you tell me how to install the package and how can I apply the `image source` script in my project.

**Comment by keijiro** [comment]
First of all, what's the reason for you trying to use this package?

This is not an easy-to-use/ready-for-use package. It's designed solely for personal use, so it wouldn't useful for others... especially for newcomers.

**Comment by Vector3q** [comment]
Thank you for reply, I just want to follow your work named TinyYOLOv2Barracuda.

Through this, I can develop a selfie application which requires Yolov2 model.  

I just copied your folder named "jp.keijiro.klak.testtools" in the Packages to my own Packages,
Fortunately, it did not report any errors.

**Comment by keijiro** [comment]
Okay. Then I close this issue.
